### ISSUE TITLE
snapshot using volume buttons

### ISSUE THREAD

**Issue by mythodeia** [ArcRain/JournyCam#1]
Hello Sora,
great feature. 
I found one small bug.
if you open an audio source like for example Music and play radio then open your app while the radio is still playing the volume buttons capture the image but the HUD is showing.
can you try it?

is [this](https://github.com/ArcRain/JournyCam/commit/1d6c1321068b3851112bc40512ce696ee56d4746#diff-7279a2048c6317d07c62237b97462a40R244) safe for appstore? i haven't seen that technique anywhere :)

**Comment by ArcRain** [comment]
I'll try it later.
I found this method from [here](http://stackoverflow.com/questions/26302218/hide-volume-hud-in-ios-8)
I'm not sure whether it's safe.
